joy_teleop:
  ros__parameters:

    drive:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: /teleop
      axis_mappings:
        drive-speed:
          axis: 1
          scale: 2.0
          offset: 0.0
        drive-steering_angle:
          axis: 3
          scale: -0.34
          offset: 0.0
        header-frame_id:
          value: "base_link"

    brake:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: /teleop
      deadman_buttons: [4]
      message_value:
        drive-speed:
          value: 0.0
        drive-steering_angle:
          value: 0.0
        header-frame_id:
          value: "base_link"

    switch_to_autonomous:
      type: topic
      interface_type: std_msgs/msg/Bool
      topic_name: /autonomous_mode
      deadman_buttons: [1]  # B button
      message_value:
        data: true

    switch_to_manual:
      type: topic
      interface_type: std_msgs/msg/Bool
      topic_name: /autonomous_mode
      deadman_buttons: [0]  # A button
      message_value:
        data: false

    boost_mode:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: /teleop
      deadman_buttons: [3]
      message_value:
        drive-speed:
          value: 1.0
        drive-steering_angle:
          value: 0.0
        header-frame_id:
          value: "base_link"
